apiVersion: v1
kind: Service
metadata:
    name: node-example-routine-service
spec:
    selector:
        app: node-example-routine
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
