apiVersion: v1
kind: Service
metadata:
    name: node-example-user-service
spec:
    selector:
        app: node-example-user
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000
