apiVersion: apps/v1
kind: Deployment
metadata:
    name: nosqldb-deployment
    labels:
        app: nosqldb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nosqldb
    template:
        metadata:
            labels:
                app: nosqldb
        spec:
            containers:
                - name: nosqldb
                  image: mongo:latest
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: node-example-secret
                                key: DB_NO_SQL_USER_NAME
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: node-example-secret
                                key: DB_NO_SQL_PASSWORD
